# Generated by Django 4.2 on 2024-01-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_order_cart_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
    ]
